<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robofetch_bringup</name>
  <version>0.1.0</version>
  <description>Top-level launch files that start the complete RoboFetch system.</description>
  <maintainer email="shafagh.arian2003@gmail.com">robojazzy</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robofetch_gazebo</exec_depend>
  <exec_depend>robofetch_nav</exec_depend>
  <exec_depend>robofetch_core</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
