#!/usr/bin/env python3
"""Generate the warehouse occupancy grid directly from the world geometry.

The proposal specifies a *known static map* for Nav2/AMCL (SLAM-based exploration is
listed as a future extension), so the map is produced analytically from the same wall
definitions used in robofetch_gazebo/worlds/warehouse.sdf rather than being scanned.

Advantages over a SLAM-built map:
  * zero drift - walls are exactly where the simulator puts them
  * the map frame is identical to the Gazebo world frame, so waypoints can be written
    in world coordinates (point A = (-2.2, -2.2), point B = (2.2, 2.2))
  * perfectly repeatable - no manual driving involved

Outputs maze.pgm + maze.yaml in robofetch_nav/maps/.

Keep the WALLS list below in sync with warehouse.sdf.
"""
import os

from PIL import Image, ImageDraw

# --- Must mirror robofetch_gazebo/worlds/maze.sdf -------------------------------------
# Each wall: (centre_x, centre_y, size_x, size_y) in metres, world frame.
WALLS = [
    # Outer walls of the 8 x 6 m room (rectangular on purpose: a square room is
    # rotationally ambiguous to a lidar and makes AMCL jump between poses).
    (0.0,  3.0, 8.1, 0.1),    # wall_north
    (0.0, -3.0, 8.1, 0.1),    # wall_south
    (4.0,  0.0, 0.1, 6.1),    # wall_east
    (-4.0, 0.0, 0.1, 6.1),    # wall_west
    # Shelves. These are real obstacles AND the features that make each part of the
    # room look distinctive to the laser, which is what keeps localization stable.
    # All three are FLUSH against a wall. Standing a shelf off the wall leaves a corridor
    # too narrow for the robot to turn around in, which strands it and wrecks localization.
    (-2.5, 2.25, 2.0, 1.4),   # shelf_1  north-west, long,    flush to the north wall
    (1.5,  2.25, 1.5, 1.4),   # shelf_2  north-east, shorter, flush to the north wall
    (3.6, -1.0,  0.5, 2.0),   # shelf_3  east, rotated 90 deg, flush to the east wall
    # NOTE: delivery_station is a floor marking only - deliberately NOT an obstacle.
]

RESOLUTION = 0.05          # m per pixel (matches Nav2 costmap resolution)
MARGIN = 0.5               # m of border around the arena
ARENA_HALF_X = 4.05        # outer face of the east/west walls
ARENA_HALF_Y = 3.05        # outer face of the north/south walls

# Standard map_server greyscale values.
FREE, OCCUPIED, UNKNOWN = 254, 0, 205


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out_dir = os.path.join(here, "..", "src", "robofetch_nav", "maps")
    out_dir = os.path.normpath(out_dir)
    os.makedirs(out_dir, exist_ok=True)

    extent_x = ARENA_HALF_X + MARGIN
    extent_y = ARENA_HALF_Y + MARGIN
    origin_x, origin_y = -extent_x, -extent_y
    width_px = int(round((2 * extent_x) / RESOLUTION))
    height_px = int(round((2 * extent_y) / RESOLUTION))

    def to_px(wx, wy):
        """World metres -> pixel (col, row). PGM row 0 is the TOP, so y is flipped."""
        col = (wx - origin_x) / RESOLUTION
        row = height_px - (wy - origin_y) / RESOLUTION
        return col, row

    # Start with everything unknown, then carve the arena interior as free.
    img = Image.new("L", (width_px, height_px), UNKNOWN)
    draw = ImageDraw.Draw(img)

    c0, r0 = to_px(-ARENA_HALF_X, -ARENA_HALF_Y)
    c1, r1 = to_px(ARENA_HALF_X, ARENA_HALF_Y)
    draw.rectangle([min(c0, c1), min(r0, r1), max(c0, c1), max(r0, r1)], fill=FREE)

    # Stamp the walls as occupied.
    for cx, cy, sx, sy in WALLS:
        a_c, a_r = to_px(cx - sx / 2.0, cy - sy / 2.0)
        b_c, b_r = to_px(cx + sx / 2.0, cy + sy / 2.0)
        draw.rectangle([min(a_c, b_c), min(a_r, b_r), max(a_c, b_c), max(a_r, b_r)],
                       fill=OCCUPIED)

    pgm_path = os.path.join(out_dir, "warehouse.pgm")
    yaml_path = os.path.join(out_dir, "warehouse.yaml")
    img.save(pgm_path)

    with open(yaml_path, "w") as fh:
        fh.write(
            "# Generated by scripts/generate_map.py from the warehouse.sdf geometry.\n"
            "# Do not hand-edit: re-run the script if the world changes.\n"
            "image: warehouse.pgm\n"
            "mode: trinary\n"
            f"resolution: {RESOLUTION}\n"
            f"origin: [{origin_x}, {origin_y}, 0.0]\n"
            "negate: 0\n"
            "occupied_thresh: 0.65\n"
            "free_thresh: 0.196\n"
        )

    print(f"wrote {pgm_path}  ({width_px}x{height_px} px, {2*extent_x:.1f}x{2*extent_y:.1f} m)")
    print(f"wrote {yaml_path} (origin {origin_x}, {origin_y})")
    print("map frame == Gazebo world frame, so waypoints are world coordinates.")


if __name__ == "__main__":
    main()
